### PR TITLE
Silence errors from VSIL handler

### PR DESCRIPTION
**Pull request by jdmcbr**
Taken from now-closed PR #28. Since these errors are slightly
distracting during testing, nice to quiet them.

### CODE REVIEW

**Comment by sgillies** [comment]
@jdmcbr the errors only show up due to a rasterio bug that will be fixed in 1.0. Could you make a note of that in the code?

**Comment by jdmcbr** [comment]
@sgillies Ah, I hadn't revisited that issue you logged on gdal, I didn't realize it was a `rasterio` error.

**Comment by sgillies** [comment]
The rasterio fix is here: https://github.com/mapbox/rasterio/pull/1201.

**Comment by jdmcbr** [comment]
Great, updated to master, thanks!

**Pull request closed without merging**
